# Generated by Django 6.0.2 on 2026-02-20 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Engineers who can access and edit tasks on this board.', related_name='shared_boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='board',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('finished', 'Finished')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='card',
            name='assignee',
            field=models.ForeignKey(blank=True, help_text='Engineer responsible for this task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='discipline',
            field=models.CharField(blank=True, choices=[('mec', 'Mecánica'), ('elec', 'Eléctrica'), ('auto', 'Automatización'), ('refrig', 'Refrigeración')], max_length=10),
        ),
        migrations.AddField(
            model_name='card',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, help_text='Completion percentage (0-100).'),
        ),
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('backlog', 'Backlog'), ('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'Review'), ('done', 'Done')], default='backlog', max_length=20),
        ),
        migrations.AlterField(
            model_name='board',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='column',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='BoardAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_at', models.DateTimeField(auto_now_add=True)),
                ('total_cards', models.IntegerField(default=0)),
                ('completed_cards', models.IntegerField(default=0)),
                ('overdue_cards', models.IntegerField(default=0)),
                ('avg_progress', models.FloatField(default=0.0, help_text='Average progress % across all cards at time of closing.')),
                ('discipline_stats', models.JSONField(blank=True, default=dict)),
                ('board', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='tasks.board')),
            ],
        ),
    ]
